config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :options
  resources :deliveryoptions
  resources :bookings

  get 'all' => 'bookings#all', as: :all
  post 'cleanup' => 'bookings#cleanup', as: :cleanup
  post 'provide' => 'bookings#cleanup', as: :provide

  resources :users do
    collection { get :search, :request_reset, :reset_password }
    collection { post :request_reset, :reset_password }
  end
  get '/users/:id/reset_password/:onetimetoken(.:format)' => 'users#reset_password', as: 'reset'

  resources :sessions
  post 'logout' => 'sessions#destroy'

  get '/about' => 'application#about'

  root 'bookings#index'

end

app/models/booking.rb
# encoding: UTF-8
class Booking < ActiveRecord::Base

  belongs_to :company
  belongs_to :deliveryoption

  validates_presence_of :lwohnort, :birthdate, :lsdate, :vname, :nname, :ddate
  validates :ddate, uniqueness: {:message => :already_registered, scope: [:vname, :nname, :ddate]}
  validate :zeitlAblauf

  def zeitlAblauf
      if self.ddate != nil && self.ddate != "" && self.ddate > Time.now
        errors.add(:ddate, :future)
      end
      if self.bdate != nil && self.bdate != "" && self.ddate != nil && self.ddate != "" && self.bdate < self.ddate + 48.hours
        if self.btime != nil
          if self.btime.strftime("%H:%M") < self.ddate.strftime("%H:%M")
            errors.add(:bdate, :twodays)
          end
        elsif self.bdate < self.ddate + 24.hours
          errors.add(:bdate, :twodays)
        end
      end
      if self.lsdate != nil && self.lsdate != "" && self.bdate != nil && self.bdate != "" && self.lsdate.to_date > self.bdate
        errors.add(:lsdate, :before_bdate)
      end
      if self.lsdate != nil && self.lsdate != "" && self.bdate != nil && self.bdate != "" && self.lsdate.to_date == self.bdate
        if self.lsdate.strftime("%H:%M").to_time > "10:00".to_time
          errors.add(:lsdate, :eq_bdate)
        end
        if self.lseqb > 4
          errors.add(:lsdate, :to_many)
        end
      end
      if self.lsdate != nil && self.lsdate != "" && self.ddate != nil && self.ddate != "" && self.lsdate < self.ddate
        errors.add(:lsdate, :before_ddate)
      end
      if self.wludate != nil && self.wludate != "" && self.bdate != nil && self.bdate != "" && self.wludate <= (self.bdate.to_datetime) + 1.days + 9.hours + 59.minutes && self.approved != true
        errors.add(:wludate, :wlu_on_bdate)
      end
      if self.wludate != nil && self.wludate != "" && self.bdate != nil && self.bdate != "" && self.wludate < (self.bdate.to_datetime)
        errors.add(:wludate, :wlu_before_bdate)
      end
      if self.ddate != nil && self.ddate != "" && self.birthdate != nil && self.birthdate != "" && self.birthdate > self.ddate
        errors.add(:birthdate, :before_ddate)
      end
  end

  def lseqb
    Booking.where("lsdate >= ?", self.bdate).size
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @dailybookings = {}
    @range = (Date.today..Date.today + Option.first.bdates)
    @range.each do |d|
      @dailybookings[d] = bookable_slots(d) - Booking.where(bdate: d).count
    end
  end

  def all
    @title = t(:bookings)
    if @current_user.role == 3
      @bookings = Booking.where( company_id: @current_user.company_id )
    else
      if params[:datum] && params[:datum] != ""
        @title = "Buchungen für den #{l(params[:datum].to_date)}"
        @bookings = Booking.where( bdate: params[:datum].to_date).order('btime ASC')
      else
        @bookings = Booking.all.order('bdate ASC')
      end
      @deletables_count = Booking.where("bdate < ?", Time.now - 3.days).count
    end
  end

  def cleanup
    Booking.where("bdate < ?", Time.now - 3.days).each do |oldbk|
      oldbk.destroy
    end
    redirect_to all_path
  end
  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    if @current_user.role == 3
      @booking = Booking.new( company_id: @current_user.company_id )
    else
      @booking = Booking.new
    end
    @booking.bdate = params[:datum]
    @booking.wludate = @booking.bdate.to_date + 1.days + 10.hours
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.created_by = @current_user.nname + ", " + @current_user.vname

    respond_to do |format|
      # format.js
      if @booking.save
        format.html { redirect_to bookings_path, notice: 'Die Buchung wurde im System gespeichert.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to all_path, notice: 'Die Buchung wurde aktualisiert.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to all_path, notice: 'Die Buchung wurde gelöscht.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:company_id, :approved, :ddate, :vname, :nname, :birthdate, :lwohnort, :lsdate, :wludate, :bdate, :btime, :deliveryoption_id)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= @booking.errors.count %> Fehler</h2>

      <ul>
      <% @booking.errors.each do |e,message| %>
        <% if message == t("activerecord.errors.models.booking.attributes.nname.already_registered") %>
          <li><%= message %></li>
        <% else %>
          <% if message == t("activerecord.errors.models.booking.attributes.wludate.wlu_on_bdate") %>
            <% @vis = "visibility:visible;" %>
          <% end %>
          <li><%= t("activerecord.attributes.booking.#{e}") %> : <%= message %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @vis = "visibility:visible;" if @booking.approved == true %>

  <% if @current_user.role == 3 %>
    <h2>Buchung für <%= @booking.company.name %></h2>
    <%= f.hidden_field :company_id %>
    <aside class="hinweis">
      Bitte beachten Sie: Eine Kremation ist nur mit ärztlicher Todesbescheinigung und Kremationsauftrag möglich!
    </aside>
  <% else %>
    <h2>Buchung für: </h2>
    <%= f.collection_select(:company_id, Company.all, :id, :name) %> (oder erst <%= link_to "neue Firma anlegen?", new_company_path %>)
  <% end %>

  <table id="ddata">
  <tr>
    <th colspan="3">
      Angaben zum / zur Verstorbenen
    </th>
  </tr>
  <tr>
    <td class="field" style="width: 340px;">
      <%= t(:dvname) %><br>
      <%= f.text_field :vname %>
    </td>
    <td class="field">
      <%= t(:dnname) %><br>
      <%= f.text_field :nname %>
    </td>
    <td class="field">
      <%= t(:birthdate) %><br>
      <%= f.date_field :birthdate, placeholder: "dd.mm.YYYY", value: (@booking.birthdate.nil? ? nil : l(@booking.birthdate)) %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= t(:lwohnort) %><br>
      <%= f.text_field :lwohnort %>
    </td>
    <td colspan="2" class="field">
      <%= t(:ddate) %><br>
      <%= f.datetime_select :ddate %>
    </td>
  </tr>
  </table>
  <table id="ldata">
  <tr>
    <th colspan="3">
      Angaben zur Lieferung
    </th>
  </tr>
  <tr>
    <td class="field" style="width: 340px;">
      <%= t(:lsdate) %><br>
      <%= f.datetime_select :lsdate %>
    </td>
    <% if @current_user.is_admin %>
      <td class="field">
        <%= t(:bdate) %><br>
        <%= f.date_select :bdate %>
      </td>
      <td>
        <%= t(:btime) %><br>
        <%= f.time_field :btime, placeholder: "HH:MM", value: (@booking.btime.nil? ? nil : l(@booking.btime)) %>
      </td>
    <% else %>
      <td class="field" colspan="2">
        <%= t(:bdate) %><br>
        <%= l( @booking.bdate ) %>
        <%= f.hidden_field :bdate %>
      </td>
    <% end %>
  </tr>

  <tr>
    <td class="field">
      <%= t(:wludate) %><br>
      <%= f.datetime_select :wludate %>
    </td>
    <td  colspan="2" class="field">
      <aside class="wichtig" style="<%= @vis %>">Ja, ich habe das mit einem Mitarbeiter des Krematoriums abgesprochen.<%= f.check_box :approved %> </aside>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= t(:deliveryoption) %><br>
      <%= f.collection_select(:deliveryoption_id, Deliveryoption.all, :id, :deloption ) %>
    </td>
    <td colspan="2">
      <aside id="del_info"></aside>
    </td>
  </tr>
  <tr>
    <td class="submit">
      <%= f.submit %>
    </td>
    <td></td>
    <td>
      <% unless current_page?(new_booking_path) %>
        <%= link_to 'Diese Buchung löschen', @booking, method: :delete, data: { confirm: 'Sind Sie sicher?' }, style: "color:darkred;" %>
      <% end %>
    </td>
  </tr>
</table>

<% end %>

app/views/bookings/_tag.html.erb
<article class="tag">
  <aside class="open"><%= @dailybookings[d] %></aside>
  <%= dayname(d.wday) %><br>
  <%= d.strftime("%d.%m.%Y") %>
</article>

app/views/bookings/all.html.erb
<article>
<table class="liste">
  <thead>
    <tr>
      <th><%= t(:company) %></th>
      <th><%= t(:dname) %></th>
      <th><%= t(:ddate) %></th>
      <th><%= t(:lsdate ) %></th>
      <th><%= t(:bdate ) %></th>
      <th><%= t(:wludate ) %></th>
      <th><%= t(:deliveryoption ) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <% if booking.wludate <= booking.bdate.to_datetime  + 1.days + 9.hours + 59.minutes %>
        <tr class="wichtig" style="visibility:visible;">
      <% else %>
        <tr>
      <% end %>
        <td><%= booking.company.name %></td>
        <td><%= booking.vname %> <%= booking.nname %></td>
        <td><%= l(booking.ddate, format: :datetime) %></td>
        <td><%= l(booking.lsdate, format: :datetime) %></td>
        <td><%= link_to l(booking.bdate), all_path(datum: booking.bdate) %>
          <% if booking.btime %>
            , <%= l(booking.btime) %>
          <% end %></td>
        <td><%= l(booking.wludate, format: :datetime) %></td>
        <td><%= booking.deliveryoption.deloption %></td>
        <td class="functions">
          <%= link_to 'Edit', edit_booking_path(booking), class: "no_print" %><br>
          <% if booking.provided %>
            <% if booking.deliveryoption_id == 3 %>
              versendet
            <% else %>
              bereitgestellt
            <% end %>
          <% else %>
            <%= link_to 'abschliessen', provide_path(booking), method: :post, class: "no_print" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to("Liste drucken", "javascript:print()", class: "no_print") %>
</article>

app/views/bookings/edit.html.erb
<%= render 'form' %>

app/views/bookings/index.html.erb
<article class="kommendetage">
  <% @range.each do |d| %>
    <% if d == Date.today || @dailybookings[d] < 1 %>
      <%= render "tag", :d => d %>
    <% else %>
      <a href=<%= new_booking_path(datum: d) %>><%= render "tag", :d => d %></a>
    <% end %>  
  <% end %>
</article>

app/views/bookings/new.html.erb
<article>
<%= render 'form' %>
</article>

app/views/bookings/show.html.erb
<p>
  <strong>User:</strong>
  <%= @booking.user_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @booking.name %>
</p>

<p>
  <strong>Ddate:</strong>
  <%= @booking.ddate %>
</p>

<p>
  <strong>Ldate:</strong>
  <%= @booking.bdate %>
</p>

<p>
  <strong>Bdate:</strong>
  <%= @booking.bdate %>
</p>

<p>
  <strong>Ldate:</strong>
  <%= @booking.wludate %>
</p>

<p>
  <strong>Auslieferung:</strong>
  <%= @booking.deliveryoption.deloption %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>