config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :options
  resources :deliveryoptions
  resources :bookings

  get 'all' => 'bookings#all', as: :all
  post 'cleanup' => 'bookings#cleanup', as: :cleanup
  post 'provide' => 'bookings#cleanup', as: :provide

  resources :users do
    collection { get :search, :request_reset, :reset_password }
    collection { post :request_reset, :reset_password }
  end
  get '/users/:id/reset_password/:onetimetoken(.:format)' => 'users#reset_password', as: 'reset'

  resources :sessions
  post 'logout' => 'sessions#destroy'

  get '/about' => 'application#about'

  root 'bookings#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  
  has_many :users
  has_many :bookings
  
  validates_presence_of :name, :strasse, :hnr, :plz, :ort, :tel, :email
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :user_id, :booking_id, :strasse, :hnr, :plz, :ort, :tel, :email)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
  <tr>
    <td colspann="2" class="field">
      <%= f.label :name %><br>
       <%= f.text_field :name %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :strasse %><br>
      <%= f.text_field :strasse %>
    </td>
    <td class="field">
      <%= f.label :hnr %><br>
      <%= f.text_field :hnr %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :plz %><br>
      <%= f.text_field :plz %>
    </td>
    <td class="field">
      <%= f.label :ort %><br>
      <%= f.text_field :ort %>
    </td>
  </tr>
  <tr>
    <td class="field">
      <%= f.label :tel %><br>
      <%= f.text_field :tel %>
    </td>
    <td class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </td>
  </tr>
  <tr>
    <td colspann="2" class="actions">
     <%= f.submit %>
    </td>
  </tr>
  </table>
<% end %>

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liste der Bestattungsunternehmen</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Anschrift</th>
      <th>Telefon</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, edit_company_path(company) %></td>
        <td><%= "#{company.strasse} #{company.hnr}, #{company.plz} #{company.ort}" %></td>
        <td><%= company.tel %></td>
        <td><%= company.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Neues Unternehmen', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Strasse:</strong>
  <%= @company.strasse %>
</p>

<p>
  <strong>Hnr:</strong>
  <%= @company.hnr %>
</p>

<p>
  <strong>Plz:</strong>
  <%= @company.plz %>
</p>

<p>
  <strong>Ort:</strong>
  <%= @company.ort %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @company.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @company.email %>
</p>

<%= link_to 'bearbeiten', edit_company_path(@company) %>